### PR TITLE
Fix syntax error

### PR DESCRIPTION
**Pull request by dcadenas**
I found out that the current swift files have some syntax errors, multiple `throws try`. They are easy to fix so I went ahead and did it manually but it seems that some steps are failing to produce correct output.

I also noticed that some functions like `EventBuilder::gift_wrap_from_seal` where not included, is this expected or somehow not all features got activated?

### CODE REVIEW

**Comment by yukibtc** [comment]
Seems that `throws` miss only to the constructors. The `.swift` file are composed automatically by UniFFI. I'll try to check what's wrong.

---

I'm going to add `gift_wrap_from_seal` (will be available in the next version, alternatively you can compile the bindings by yourself). UniFFI allow only to return `Self` for constructors, so it will not available in `EventBuilder` but will be a function (like the `gift_wrap` func).

**Comment by yukibtc** [comment]
The `throws` issue not happen in the `v0.10.0` right?

**Comment by yukibtc** [comment]
Just saw that `throws` issue is fixed in `UniFFI` v0.27.1 (<https://github.com/mozilla/uniffi-rs/commit/910ddcd8bef58c12b08a4e1364ea7633794b3063>).

I'm going to bump it and release a new Swift Package

**Comment by yukibtc** [comment]
I just released v0.11.1

It include also the `gift_wrap_from_seal` function

**Comment by dcadenas** [comment]
Wow that was a quick response, thanks! 🙇‍♂️

**Comment by yukibtc** [comment]
No problem :)

Let me know if works (I haven't a mac so I can't test it).

**Comment by dcadenas** [comment]
It worked ! I couldn't find the gift_wrap_from_seal export though but for the moment we won't need it.

**Pull request closed without merging**
